sudo: false
language: python

python: 3.5
cache: pip
env:
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=py35
    - TOXENV=pypy
    - TOXENV=docs
    - TOXENV=pep8
    - TOXENV=coverage
install:
    - pip install -r travis_requirements.txt
script:
    - tox -e $TOXENV
