sudo: false
language: python

python: 3.5
env:
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=py35
    - TOXENV=pypy
    - TOXENV=docs
    - TOXENV=pep8
    - TOXENV=coverage
install:
    - pip install --upgrade pip setuptools
    - pip install tox
script:
    - tox -c .travis_tox.ini -e $TOXENV
